#!/usr/bin/env bash
# Install nginx on your server
sudo apt-get -y update
sudo apt-get -y install nginx
#echo "Hello World!" | sudo tee /var/www/html/index.html
curl "Hello World!" | sudo tee /var/www/html/index.html
service nginx restart
