#!/usr/bin/env bash
# Update the package list to ensure we have the latest information
sudo apt-get update

# Install nginx on the server
sudo apt-get -y update

sudo apt-get -y install nginx

# Create a custom Nginx configuration to return "Hello World!" on the root path
echo "server {
    listen 80;
    server_name _;

    location / {
        return 200 'Hello World!';
    }
}" | sudo tee /etc/nginx/sites-available/default > /dev/null

#echo "Hello World!" | sudo tee /var/www/html/index.html

# Restart Nginx to apply the new configuration

sudo service nginx start
