#!/usr/bin/env bash
# Update the package list to ensure we have the latest information
sudo apt-get update

# Install nginx on the server
sudo apt-get -y update

sudo apt-get -y install nginx

# Create a custom Nginx configuration to return "Hello World!" on the root path
echo "server {
    listen 80 default server;
    server_name _;

    location / {
    	index index.html;
    }
}" | sudo tee /var/www/html/index.html > /dev/null

# echo "Hello World!" | sudo tee /var/www/html/index.html

# Restart Nginx to apply the new configuration

sudo service nginx start
