#!/usr/bin/env bash
# config nginx on your server web-02
sudo apt-get update
sudo apt-get install nginx
echo "School" | sudo tee /var/www/html/index.html
sudo sed -i "15i \\\tadd_header X-Served-By 334278-web-02;" /etc/nginx/nginx.conf
sudo service nginx restart
sudo service nginx start
