#!/usr/bin/env bash
# install and configure load balancer for web-01 and web-02
sudo apt-get -y install software-properties-common
sudo add-apt-repository ppa:vbernat/haproxy-1.8
sudo apt-get update
sudo apt-get -y install haproxy=1.8.\*
echo "frontend http
        mode http
        bind *:80
        default_backend web-backend

    backend web-backend
        balance roundrobin
        server 334278-web-01 100.26.9.130:80 check
        server 334278-web-02 34.204.91.51:80 check" >> /etc/haproxy/haproxy.cfg
sudo service haproxy restart
