#!/usr/bin/env bash

start_process() {
  if [ -f "/var/run/my_process.pid" ]; then
    echo "Error: manage_my_process is already running."
  else
    ./manage_my_process &
    echo $! > /var/run/my_process.pid
    echo "manage_my_process started."
  fi
}

stop_process() {
  if [ -f "/var/run/my_process.pid" ]; then
    pid=$(cat /var/run/my_process.pid)
    kill $pid
    rm /var/run/my_process.pid
    echo "manage_my_process stopped."
  else
    echo "Error: manage_my_process is not running."
  fi
}

restart_process() {
  stop_process
  start_process
  echo "manage_my_process restarted."
}

case $1 in
  start)
    start_process
    ;;
  stop)
    stop_process
    ;;
  restart)
    restart_process
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
    ;;
esac
