#!/usr/bin/env bash
# Fix this container so that Nginx is running as the nginx user small.
pkill apache2
chown nginx /etc/nginx/nginx.conf
chmod u+r /etc/nginx/nginx.conf
sed -i 's/80/8080/' /etc/nginx/sites-available/default
sudo -u nginx service nginx restart
